version: '3'
services:
  web:
    container_name: server1
    env_file: .env
    build: .
    expose:
      - 5000
    ports:
      - 5000:5000
    depends_on:
      - db
  db:
    container_name: database1
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_DB=${DB}
      - POSTGRES_HOST=${HOST}
    expose:
      - 5432
    ports:
      - 5432:5432
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080