/**
 * Weatherbit.io - Swagger UI Weather API documentation
 * This is the documentation for the Weatherbit Weather API.  The base URL for the API is [http://api.weatherbit.io/v2.0/](http://api.weatherbit.io/v2.0/) or [https://api.weatherbit.io/v2.0/](http://api.weatherbit.io/v2.0/). Below is the Swagger UI documentation for the API. All API requests require the `key` parameter.        An Example for a 5 day forecast for London, UK would be `http://api.weatherbit.io/v2.0/forecast/3hourly?city=London`&`country=UK`. See our [Weather API description page](https://www.weatherbit.io/api) for additional documentation.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ForecastWeather } from './forecastWeather';


export interface Forecast { 
    /**
     * Unix Timestamp
     */
    ts?: number;
    /**
     * Timestamp in local time
     */
    timestamp_local?: string;
    /**
     * Timestamp UTC
     */
    timestamp_utc?: string;
    /**
     * Date in format \"YYYY-MM-DD:HH\". All datetime is in (UTC)
     */
    datetime?: string;
    /**
     * Accumulated snowfall since last forecast point - default (mm)
     */
    snow?: number;
    /**
     * Snow Depth - default (mm)
     */
    snow_depth?: number;
    /**
     * Accumulated precipitation since last forecast point - default (mm)
     */
    precip?: number;
    /**
     * Temperature (Average) - default (C)
     */
    temp?: number;
    /**
     * Dewpoint (Average) - default (C)
     */
    dewpt?: number;
    /**
     * Maximum daily Temperature - default (C)
     */
    max_temp?: number;
    /**
     * Minimum daily Temperature - default (C)
     */
    min_temp?: number;
    /**
     * Apparent Maximum daily Temperature - default (C)
     */
    app_max_temp?: number;
    /**
     * Apparent Minimum daily Temperature - default (C)
     */
    app_min_temp?: number;
    /**
     * Relative Humidity as a percentage (%)
     */
    rh?: number;
    /**
     * Cloud cover as a percentage (%)
     */
    clouds?: number;
    weather?: ForecastWeather;
    /**
     * Mean Sea level pressure (mb)
     */
    slp?: number;
    /**
     * Pressure (mb)
     */
    pres?: number;
    /**
     * UV Index
     */
    uv?: number;
    /**
     * [Deprecated] Max direct component of solar insolation (W/m^2)
     */
    max_dhi?: number;
    /**
     * Average Visibility default (KM)
     */
    vis?: number;
    /**
     * Chance of Precipitation as a percentage (%)
     */
    pop?: number;
    /**
     * Moon phase
     */
    moon_phase?: number;
    /**
     * Sunrise unix timestamp
     */
    sunrise_ts?: number;
    /**
     * Sunset unix timestamp
     */
    sunset_ts?: number;
    /**
     * Moonrise unix timestamp
     */
    moonrise_ts?: number;
    /**
     * Moonset unix timestamp
     */
    moonset_ts?: number;
    /**
     * Part of the day (d = day, n = night)
     */
    pod?: string;
    /**
     * Wind Speed (default m/s)
     */
    wind_spd?: number;
    /**
     * Wind direction
     */
    wind_dir?: number;
    /**
     * Cardinal wind direction
     */
    wind_cdir?: string;
    /**
     * Cardinal wind direction (text)
     */
    wind_cdir_full?: string;
}

