/**
 * Weatherbit.io - Swagger UI Weather API documentation
 * This is the documentation for the Weatherbit Weather API.  The base URL for the API is [http://api.weatherbit.io/v2.0/](http://api.weatherbit.io/v2.0/) or [https://api.weatherbit.io/v2.0/](http://api.weatherbit.io/v2.0/). Below is the Swagger UI documentation for the API. All API requests require the `key` parameter.        An Example for a 5 day forecast for London, UK would be `http://api.weatherbit.io/v2.0/forecast/3hourly?city=London`&`country=UK`. See our [Weather API description page](https://www.weatherbit.io/api) for additional documentation.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ForecastHourWeather } from './forecastHourWeather';


export interface ForecastHour { 
    /**
     * Unix Timestamp
     */
    ts?: number;
    /**
     * Timestamp in local time
     */
    timestamp_local?: string;
    /**
     * Timestamp UTC
     */
    timestamp_utc?: string;
    /**
     * Date in format \"YYYY-MM-DD:HH\". All datetime is in (UTC)
     */
    datetime?: string;
    /**
     * Accumulated snowfall since last forecast point - Default (mm)
     */
    snow?: number;
    /**
     * Snow depth - Default (mm)
     */
    snow_depth?: number;
    /**
     * 6 hour accumulated snowfall. Default (mm)
     */
    snow6h?: number;
    /**
     * Accumulated precipitation since last forecast point. Default (mm)
     */
    precip?: number;
    /**
     * Temperature - Default (C)
     */
    temp?: number;
    /**
     * Dewpoint - Default (C)
     */
    dewpt?: number;
    /**
     * Apparent Temperature - Default (C)
     */
    app_temp?: number;
    /**
     * Relative Humidity as a percentage (%)
     */
    rh?: number;
    /**
     * Cloud cover as a percentage (%)
     */
    clouds?: number;
    weather?: ForecastHourWeather;
    /**
     * Mean Sea level pressure (mb)
     */
    slp?: number;
    /**
     * Pressure (mb)
     */
    pres?: number;
    /**
     * UV Index
     */
    uv?: number;
    /**
     * Estimated solar radiation (W/m^2)
     */
    solar_rad?: number;
    /**
     * Global horizontal solar irradiance (W/m^2)
     */
    ghi?: number;
    /**
     * Diffuse normal solar irradiance (W/m^2)
     */
    dhi?: number;
    /**
     * Direct normal solar irradiance (W/m^2)
     */
    dni?: number;
    /**
     * Visibility - Default (KM)
     */
    vis?: number;
    /**
     * Part of day (d = day, n = night)
     */
    pod?: string;
    /**
     * Chance of Precipitation as a percentage (%)
     */
    pop?: number;
    /**
     * Wind Speed - Default (m/s)
     */
    wind_spd?: number;
    /**
     * Wind direction
     */
    wind_dir?: number;
    /**
     * Cardinal wind direction
     */
    wind_cdir?: string;
    /**
     * Cardinal wind direction (text)
     */
    wind_cdir_full?: string;
}

