/**
 * Messenger API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Group } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface GroupServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Get groups
     * 
     * @param token jwt
     */
    groupsGet(token: string, extraHttpRequestParams?: any): Observable<Array<Group>>;

    /**
     * Create group
     * 
     * @param token jwt
     * @param group 
     */
    groupsPost(token: string, group: Group, extraHttpRequestParams?: any): Observable<{}>;

}
