/**
 * Messenger API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { User } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface UserServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Get online users login
     * 
     * @param token jwt
     */
    onlineGet(token: string, extraHttpRequestParams?: any): Observable<Array<string>>;

    /**
     * Get users
     * 
     * @param token jwt
     */
    usersGet(token: string, extraHttpRequestParams?: any): Observable<Array<User>>;

}
