/**
 * Messenger API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Message } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface MessageServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Get messages
     * 
     * @param token jwt
     * @param message 
     */
    messageListPost(token: string, message: Message, extraHttpRequestParams?: any): Observable<Array<Message>>;

    /**
     * Send message
     * 
     * @param token jwt
     * @param message 
     */
    messagePost(token: string, message: Message, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Update message status
     * 
     * @param token jwt
     * @param messagesId 
     */
    messageStatusPut(token: string, messagesId: Array<number>, extraHttpRequestParams?: any): Observable<{}>;

}
