/**
 * Weatherbit.io - Swagger UI Weather API documentation
 * This is the documentation for the Weatherbit Weather API.  The base URL for the API is [http://api.weatherbit.io/v2.0/](http://api.weatherbit.io/v2.0/) or [https://api.weatherbit.io/v2.0/](http://api.weatherbit.io/v2.0/). Below is the Swagger UI documentation for the API. All API requests require the `key` parameter.        An Example for a 5 day forecast for London, UK would be `http://api.weatherbit.io/v2.0/forecast/3hourly?city=London`&`country=UK`. See our [Weather API description page](https://www.weatherbit.io/api) for additional documentation.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ForecastHourly } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface Class120HourHourlyForecastServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Returns an 120 hour (hourly forecast) - Given City and/or State, Country.
     *  Returns an hourly forecast, where each point represents a one hour   period. Every point has a datetime string in the format \&quot;YYYY-MM-DD:HH\&quot;. Time is UTC. Accepts a city in the format of City,ST or City. The state, and country parameters can be provided to make the search more accurate. 
     * @param city City search.. Example - &amp;city&#x3D;Raleigh,NC or &amp;city&#x3D;Berlin,DE or city&#x3D;Paris&amp;country&#x3D;FR
     * @param key Your registered API key.
     * @param state Full name of state.
     * @param country Country Code (2 letter).
     * @param units Convert to units. Default Metric See &lt;a target&#x3D;\&#39;blank\&#39; href&#x3D;\&#39;/api/requests\&#39;&gt;units field description&lt;/a&gt;
     * @param lang Language (Default: English) See &lt;a target&#x3D;\&#39;blank\&#39; href&#x3D;\&#39;/api/requests\&#39;&gt;language field description&lt;/a&gt;
     * @param callback Wraps return in jsonp callback. Example: callback&#x3D;func
     * @param hours Number of hours to return.
     */
    forecastHourlyGet(city: string, key: string, state?: string, country?: string, units?: 'S' | 'I', lang?: 'ar' | 'az' | 'be' | 'bg' | 'bs' | 'ca' | 'cs' | 'de' | 'fi' | 'fr' | 'el' | 'es' | 'et' | 'hr' | 'hu' | 'id' | 'it' | 'is' | 'kw' | 'nb' | 'nl' | 'pl' | 'pt' | 'ro' | 'ru' | 'sk' | 'sl' | 'sr' | 'sv' | 'tr' | 'uk' | 'zh' | 'zh-tw', callback?: string, hours?: number, extraHttpRequestParams?: any): Observable<ForecastHourly>;

}
