/**
 * Messengerify API
 * powered by Flasgger
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UserData model module.
 * @module model/UserData
 * @version 0.0.1
 */
class UserData {
    /**
     * Constructs a new <code>UserData</code>.
     * @alias module:model/UserData
     */
    constructor() { 
        
        UserData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UserData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserData} obj Optional instance to populate.
     * @return {module:model/UserData} The populated <code>UserData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserData();

            if (data.hasOwnProperty('login')) {
                obj['login'] = ApiClient.convertToType(data['login'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
            if (data.hasOwnProperty('uuid')) {
                obj['uuid'] = ApiClient.convertToType(data['uuid'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} login
 */
UserData.prototype['login'] = undefined;

/**
 * @member {String} password
 */
UserData.prototype['password'] = undefined;

/**
 * @member {String} uuid
 */
UserData.prototype['uuid'] = undefined;






export default UserData;

